apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: kishoren27/my-html-app
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: html
spec:
  selector:
    app: html
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

